#: import NoTransition kivy.uix.screenmanager.NoTransition


<TodoMain>:
    id: todo_main

    ScreenManager:
        # transition: NoTransition()
        id: main_scr_manager

        Screen:
            id: scrn_splash
            name: "splash"
        Screen:
            id: scrn_login
            name: "login"
        Screen:
            id: scrn_signup
            name: "signup"
        Screen:
            id: scrn_dashboard
            name: "dashboard"